# Generated by Django 3.0.6 on 2020-06-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='usr_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
