# Generated by Django 3.0.6 on 2020-06-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rst_name', models.CharField(max_length=100)),
                ('rst_link', models.URLField()),
                ('rst_content', models.TextField()),
                ('rst_keyword', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareRes_app.category')),
            ],
        ),
    ]
